B.8 CQ8
SELECT DISTINCT ?artefactLabel ?record ?docEvent ?actorLabel ?timespanLabel
WHERE {
?artefact a gerasim:Artefact ;
rdfs:label ?artefactLabel ;
crm:P70_is_documented_in ?record .
OPTIONAL {
?digitalTwin a hdto:HC2_Heritage_Digital_Twin ;
crm:P67_refers_to ?artefact ;
crm:P94i_was_created_by ?docEvent .
OPTIONAL {
?docEvent crm:P14_carried_out_by ?actor .
?actor rdfs:label ?actorLabel .
}
OPTIONAL {
?docEvent crm:P4_has_time-span ?timespan .
?timespan rdfs:label ?timespanLabel .
}
}
}
ORDER BY ?artefactLabel
