B.1 CQ1
SELECT ?artefact ?identifierLabel ?artefactLabel
WHERE {
?artefact a gerasim:Artefact ;
crm:P1_is_identified_by ?identifier ;
rdfs:label ?artefactLabel .
?identifier rdfs:label ?identifierLabel .
}
ORDER BY ?artefact
